# Generated by Django 4.1.1 on 2022-10-05 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_delete'),
    ]

    operations = [
        migrations.CreateModel(
            name='Isobaric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isobaric_title', models.CharField(max_length=50, verbose_name='Название')),
                ('isobaric_description', models.TextField(verbose_name='Описание')),
                ('isobaric_sent_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время публикации')),
            ],
        ),
    ]
