# Generated by Django 4.1.1 on 2022-10-05 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_isobaric'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Isobaric',
            new_name='Elected',
        ),
    ]
