# Generated by Django 4.1.1 on 2022-10-05 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_rename_isobaric_elected'),
    ]

    operations = [
        migrations.RenameField(
            model_name='elected',
            old_name='isobaric_description',
            new_name='elected_description',
        ),
        migrations.RenameField(
            model_name='elected',
            old_name='isobaric_sent_at',
            new_name='elected_sent_at',
        ),
        migrations.RenameField(
            model_name='elected',
            old_name='isobaric_title',
            new_name='elected_title',
        ),
    ]
